### ISSUE TITLE
Problem when TGMM gives NaN in Positions

### ISSUE THREAD

**Issue by tobetz** [leoguignard/standalone-Mouse#3]
Dear Leo,
thanks a lot for the great analysis done in of the statistical vector flow. Great Job!!!
I am currently using TGMM and also your programs to analyse cancer cell motion in spheroids. TGMM output often gives some NaNs, and these positions kill the Delaunay's triangulation in the Gabriel Graph calculation. 
I am currently trying to extend your script to filter for the NaNs, but I am a bit worried at which stage I should do this. Do you have ever faced this problem? If so, do you have any suggestion where I could/should filter out NaN. An obvious candidate seems to be lineageTree read, but I am unsure since the programs get quite complex. 
Any suggestion how I can do this. Or maybe you could even include such a filter when reading the values from the XML files? The XML files with the problem is attached (I had to change the file extension to txt to attach it.)
[GMEMfinalResult_frame0018.txt](https://github.com/leoguignard/standalone-Mouse/files/3825428/GMEMfinalResult_frame0018.txt)

Thanks for any help, best
Timo

**Comment by leoguignard** [comment]
Dear Timo,

Thanks for reporting this issue and thanks for your appreciation of the work :) .

This repo will remain as is since it is directly linked to a publication.

That being said, the TGMMlibraries repo (which is the cause of your problem) is updated independetly, you can find the repo that is up to date [there](https://github.com/leoguignard/TGMMlibraries). I have updated it according to your comment. The solution that I choose is to ignore the segmented cells that have NaNs for their position.

I have never had any NaN issue before which means that there might be some unknown problems in your dataset. If I were you I would investigate where these NaN come from to make sure everything goes as you think it does.

Cheers, Léo.
